### PR TITLE
Gbe 494 - Make bid review lists conference-aware

### PR DESCRIPTION
**Pull request by jonkiparsky**
This commit hides bids from reviewers if they are associated with a previous conference. 
Also, a fair bit of code cleanup

### CODE REVIEW

**Comment by jonkiparsky** [comment]
@bethlakshmi I cannot reproduce the problem you reported where all classes were visible. I have a minimal setup with two conferences, one "upcoming" and the other not, and one class associated with each. The class associated with the "upcoming" conference is visible, the other is not, exactly as I'd hoped. 
Can you help me get to a more precisely reproducible case?

**Comment by bethlakshmi** [comment]
Sure - I'll send you my SQL lite DB by email.
My setup is a bit more complicated than that - 
3 Expo conferences:
 - GBE 9 - completed
 - GBE 10 - current
 - GBE 11 - upcoming & the only conference that accepts bids

Then I have a pretty broad set of bids, mixing submitted, accepted, and different types of bid subclasses.
The bids that show up in my reviewer to do list are:

    Class: Shiny thing making -> GBE10
    Class: old class ->  GBE9
    Class: Shiny thing making II -> GBE11
    Class: another class -> GBE11
    Vendor: Old vendor bid -> GBE9
    Volunteer: Betty BlaizeAdmin -> GBE9

* all are submitted
* all are in "no decision"

And 4 users
- bethlakshmi - a staff member, admin and reviewer
- betty - not staff, but has every privilege group
- newuserbetty - no privs, just a regular person
- limbo - the ticketing placeholder

The bids that show in the "need to review" area for bethlakshmi here:
http://127.0.0.1:8000/gbe

Are what I listed above and it's 1:1 with all bids that are submitted but with "no decision" and no reviews from bethlakshmi - which is perfect for last year's business logic.

I'll send the DB so you don't have to recreate everything.

**Comment by bethlakshmi** [comment]
FYI - I do see the update to put in both "ongoing" and "upcoming" conferences for review - that shows up nicely now in /class/reviewlist

I am excited for to have a filter for conference selection here, since it's hard to tell that some of these are old news (although in a real database you'd be able to see that half of these have a really old date)

**Comment by jonkiparsky** [comment]
Oh, I see it now. I was looking at the bid review list

http://127.0.0.1:8000/class/reviewlist

**Comment by jonkiparsky** [comment]
Okay, try it now. 
blaize_to_review

**Comment by bethlakshmi** [comment]
Yay!

I'm glad it is un-mysterious. :)  I was worried that one (or probably both)
of us was going (or gone) crazy.

**Comment by bethlakshmi** [comment]
Looked at it in my local - love it.
Did you want me to pull now?

There are two other things, I think, on your list:
- conference filter (jquery) for bid reviewing
- remove state changing stuff on old conferences (the lower area on "/class/review/<id>" for old conferences)

What's done already looks like a good solid piece of work worth pulling, but I don't want to mess with your plans...  are you doing separate tickets for the stuff that's left?

**Comment by bethlakshmi** [comment]
Quickie question - the new "PermissionDenied" error - is that expressed as a 403 Forbidden?

I was just playing to make sure I understand it.

**Comment by jonkiparsky** [comment]
Yes, let's go ahead and merge this and do the rest of the work on separate tickets. That'll be easier to manage.

**Comment by jonkiparsky** [comment]
Yes, PermissionDenied results in a 403.

**Pull request merged**
