### PR TITLE
GBE-872: Update requirements.txt

### PR DESCRIPTION
**Pull request by jonkiparsky**
Do the usual fandango:

syncdb or load an existing db image, run migrations, run tests with --create-db flag first time

### CODE REVIEW

**Comment by bethlakshmi** [comment]
Weird - when I rebuilt (and restored my self-destroyed local settings) then all unit tests pass.  But my server port had changed (was 8282 now, 2200).  It's hard for me to see how that happened.  There's been enough virtual machine shift and my own Mac went through an upgrade - so it could be external influences... but .. weird...

I'm game to approve it - just putting out the marker for reviewer 2

I'll keep using these settings to make sure nothing weird happens.

**Comment by jonkiparsky** [comment]
This implies that you had a machine taking to port 8282.

sent from my handy. typos are just part of the fun.

**Comment by bethlakshmi** [comment]
fair enough - we'd been doing enough different vagrant related changes recently that I started getting nervous.  I'm glad to approve - whoever hops on board after me is free to push the button. :)

**Comment by gawaineo** [comment]
Review and tested. All tests passed from runcoverage and py.test --create-db

**Pull request merged**
