### PR TITLE
Gbe 504: prevent review of non-current bid

### PR DESCRIPTION
**Pull request by jonkiparsky**
Review GBE-503 first, please. Thanks.

### CODE REVIEW

**Comment by BenignCremator** [comment]
This PR does not seem to be ready for prime time yet.  There appears to be conflicts that need hand merging to resolve, and I got a failed test when running them in individuals tests:
test_review_act_all_well  -  IntegrityError: (1048, "Column 'conference_id' cannot be null")

Seems familiar.

Batch testing, however, worked just fine, 0 fails out of 128.

**Comment by jonkiparsky** [comment]
```test_review_act_all_well - IntegrityError: (1048, "Column 'conference_id' cannot be null")
```
Clearly, merging with master will resolve this, since it's exactly the same problem that was fixed last night.

**Comment by jonkiparsky** [comment]
Merged master into this branch.

**Comment by BenignCremator** [comment]
Thanks, Jon, that was exactly what I needed.  Tests now run perfectly.  Brought up a test server, and ran through things.  Got the bid pull-downs and conference selection.  However, that was as GBE Admin.  Hijack as user did not allow me to see bid redirect as describe because the bid infra has a dependency on Brown Paper Tickets for ticketing info.  Merging anyways, because it is working elsewhere, and simulating BPT is out of scope for this issue.

**Pull request merged**
