### PR TITLE
Gbe 507: add django-hijack

### PR DESCRIPTION
**Pull request by jonkiparsky**
Django-hijack allows a superuser to "masquerade" as a non-superuser without knowing or changing their password. 

To test: build a new vagrant box on this branch, then look at the Users admin page. You should see a "hijack" button for each user. 

django-hijack is pretty configurable, but I've installed the basic out-of-the-box version here. 

More info here: https://github.com/arteria/django-hijack

### CODE REVIEW

**Comment by jonkiparsky** [comment]
Have merged with master

**Comment by bethlakshmi** [comment]
OK.  I'm blocked on this pull request.  

I read the instructions on Djano Hijack here:

https://github.com/arteria/django-hijack#hijack-using-the-hijack-button-on-the-admin-site

And 
1 - I went to the Admin site.
2 - I went to the Users
3 - I see the Hijack button on the far right
4 - I press the button

I get a 404 Page not found.
The hijack URLs are listed:

 ^hijack/ ^release-hijack/$ [name='release_hijack']
^hijack/ ^disable-hijack-warning/$ [name='disable_hijack_warning']
^hijack/ ^email/(?P<email>[^@]+@[^@]+\.[^@]+)/$ [name='login_with_email']
^hijack/ ^username/(?P<username>.*)/$ [name='login_with_username']
^hijack/ ^(?P<user_id>[\w-]+)/$ [name='login_with_id']


And the URL the button is hitting is:

http://localhost:8282/hijack/90/

Problem is the same with any user in the system that I've tried (3-4 of them)

Also I tried:

http://localhost:8282/hijack/username/scratch/

since that URL should work similarly - and same problem.

Before testing, I did a:

vagrant reload --provision

to make sure I had a fresh vagrant and installed a new db.

**Comment by bethlakshmi** [comment]
Problem solved - the django-cms urls must always be the last.
I'm curious - what was the integration testing done prior to commit?

**Comment by jonkiparsky** [comment]
Integration testing was pretty simple: build a new box on the branch, with the copy of live db, and test the functionality by hikacking various users and navigating around the system. No problems encountered.

**Pull request merged**
