### PR TITLE
GBE-906 and GBE-859 - DB scrubber and updates to aliases and dbreset 

### PR DESCRIPTION
**Pull request by bethlakshmi**
This PR adds a DB scrubber to begin removing private information from the DB files while keeping RW data, named dbscrub. Also included are updates to the dbreset script and the aliases files. dbreset resets the database, including running migrations, syncdb, and collecting static files from a single line able to be run from within a script, such as the Vagrantfile. Included aliases are rmpyc (remove compiled and cache files), pepreport (differs from pepdiff in how it calls altered files, making it works more generally), and change to runcoverage from an alias to a function to allow it to: 1: run either all tests or a selected one (just list it on the command line) and 2: tests if a DB is created, and creates one if it is missing. I have have a good bit of testing on these, but need additional eyes to find bugs and give feedback on usefulness.

——

It looked weird - like there was a pull request from master to the branch, rather than from the branch to the master.  I updated from master and that closed the original request… this is betty putting the request back - from branch to master.

### CODE REVIEW

**Comment by BenignCremator** [comment]
On 12/10/2016 05:25 PM, bethlakshmi wrote:

> In aliases
> <https://github.com/bethlakshmi/GBE2/pull/922#pullrequestreview-12356008>:
>
>>  alias dbreset='/home/vagrant/dbreset'
> +alias dbscrub='/home/vagrant/dbscrub'
>
> on my machine, this is on /vagrant, and not /home/vagrant
>
> This is after a reprovision (just in case)

*SIGH*  I forgot to add the copy into /home/vagrant into the 
Vagrantfile.  Will add it.

**Comment by bethlakshmi** [comment]
Awesome.  What is the syntax on reset to load a new sql?  I tried "dbreset -d gbe_dev -p gbeNov-2016.sql" - but it didn't reload with data.

and I get an error on the cat: 

"cat: /vagrant/expo/gbeNov-2016.sql/: Not a directory"

When I run any dbreset command.

Other than that - all is good:
other commands all work great
runcoverage is good
nothing to pepdiff

**Comment by BenignCremator** [comment]
On 12/10/2016 05:38 PM, bethlakshmi wrote:

> Awesome. What is the syntax on reset to load a new sql? I tried "dbreset
> -d gbe_dev -p gbeNov-2016.sql" - but it didn't reload with data.
>
> and I get an error on the cat:
>
> "cat: /vagrant/expo/gbeNov-2016.sql/: Not a directory"
>
> When I run any dbreset command.

'dbreset -' should work, in that it should use the default options.  -p 
is for the Path (the directory the DB file is in) and -f is the 
Filename.  -h gives full help info, and no options gives a short 
summary.  So what it is doing is assuming that the filename you are 
giving it is a directory that a db file is in.  Would you like me to add 
some more/better error tests/message and/or improve the help text?

Usage: dbreset [-] [-h] [-d database name] [-s secret] [-u username]
         [-l [path to local_settings.py]] [-f SQL file] [-p path to SQL 
file]
         [-m [migrations]]

     -   -  run dbreset entirely with defaults
     -h  -  help on dbreset (this file)
     -d  -  name of database to drop and restore, default: gbe-dev
     -s  -  secret password used to identify database user, default: secret
     -u  -  username of database user, default: django_user
     -l  -  load database name, user name, and secret from local_settings.py
                default behavior is to not load settings, and settings 
set on
                the command line over-ride these setting
     -f  -  name of file containing SQL statements and data to be restored
                can accept filename, fully qualified path, or relative path,
                default is most recent of database backup with filename 
format
                DB_backup_gbelive_*.sql
     -p  -  path to SQL file, may be fully qualified or relative, with throw
                an error is path is both specified with -p and -f,
                default: /vagrant/expo
     -r  -  DO NOT restore database from file, default is to restore 
from file
                if a database file is present
     -m  -  run migrations (and an optional space separate list of 
migrations
                to run, currently accepts 'gbe scheduler ticketing', precede
                with 'fake' to run them as --fake), does not run as default,
                currently deletes ghost migrations, then migrates all.
     -b  -  syncronize db after restoring and running migrations

**Comment by bethlakshmi** [comment]
got it!  it worked!

**Comment by bethlakshmi** [comment]
Well. Phooey... i got all hopeful, cause I saw the new checkin - but no dice - same issues here.

**Comment by bethlakshmi** [comment]
Needs a total re-review once we have time again.

**Pull request closed without merging**
