### PR TITLE
GBE-833: Default location

### PR DESCRIPTION
**Pull request by bethlakshmi**
- added “default_location” to gbe.Events
- made it available in create Generic Event form.  
- made the default location the default choice when setting up the session for an event (regardless of event type) 
- added tests for all types of create event forms (we had only generic event creation)
- added test to make sure default location is default
- fixed some class creation bugs.

### CODE REVIEW

**Comment by BenignCremator** [comment]
Functional test looks good, py.tests seems happy.  Moving on to code read-through.

**Comment by BenignCremator** [comment]
Interesting.  Biggest changes in migrations and tests.  New code looked clean.  Approve, new approver should merge.

**Comment by jonkiparsky** [comment]
PEP-8 not clean:

```
vagrant@blueprint:/vagrant$ git diff --name-only master | grep ".py" | xargs pep8 | grep -v migrations
expo/expo/settings.py:239:8: E121 continuation line under-indented for hanging indent
expo/expo/settings.py:240:11: E121 continuation line under-indented for hanging indent
expo/gbe/forms.py:62:25: E126 continuation line over-indented for hanging indent
expo/gbe/forms.py:66:25: E126 continuation line over-indented for hanging indent
expo/gbe/models/remains.py:317:80: E501 line too long (84 > 79 characters)
expo/gbe/models/remains.py:1085:17: E123 closing bracket does not match indentation of opening bracket's line
expo/scheduler/views.py:180:26: E126 continuation line over-indented for hanging indent
expo/scheduler/views.py:683:33: E126 continuation line over-indented for hanging indent
expo/tests/functions/scheduler_functions.py:64:1: E302 expected 2 blank lines, found 1
expo/tests/scheduler/test_add_event.py:93:72: E226 missing whitespace around arithmetic operator
expo/tests/scheduler/test_add_event.py:169:40: E226 missing whitespace around arithmetic operator
expo/tests/scheduler/test_add_event.py:170:47: E226 missing whitespace around arithmetic operator
vagrant@blueprint:/vagrant$ 
```

**Comment by jonkiparsky** [comment]
Apart from pep-8, this looks good. Ready to merge when pep-8 is resolved.

**Comment by BenignCremator** [comment]
Most of the Pep8 items that Jon found seem to be gone, but a couple remained.  Cleaned up those, and up some random Pep8 stuff from another file.

**Pull request merged**
