### PR TITLE
Gbe 679 cleanup

### PR DESCRIPTION
**Pull request by jonkiparsky**
Preliminary PR, as requested. This is just the tidying for GBE-679
Should be pretty straightforward. 

Actual PR for GBE-679 will follow

### CODE REVIEW

**Comment by bethlakshmi** [comment]
pepdiff = good
unit test run = good

Reading code starting now, but not likely to finish tonight.

**Comment by bethlakshmi** [comment]
Looks good all around.

@gawaineo and @BenignCremator  - could at least one of you comment and/or merge?  It looks like I'm the only one who approves.  Both of you are working in areas that will have to be merged with this, so please approve earlier rather than later.

**Comment by gawaineo** [comment]
@bethlakshmi @BenignCremator I ran this branch on my Linux Mint desktop and I'm getting the import Volunteer error ( I also made the comment in slack). On my WIndows 10 machine, all tests passed and the app runs well.

```
==> default: cat: 
==> default: /vagrant/config/
==> default: : Is a directory
==> default: Traceback (most recent call last):
==> default:   File "/vagrant/expo/manage.py", line 10, in <module>
==> default:     
==> default: execute_from_command_line(sys.argv)
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
==> default:     
==> default: utility.execute()
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
==> default:     
==> default: self.fetch_command(subcommand).run_from_argv(self.argv)
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
==> default:     
==> default: self.execute(*args, **options.__dict__)
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 280, in execute
==> default:     
==> default: translation.activate('en-us')
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/__init__.py", line 130, in activate
==> default:     
==> default: return _trans.activate(language)
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 188, in activate
==> default:     
==> default: _active.value = translation(language)
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 177, in translation
==> default:     
==> default: default_translation = _fetch(settings.LANGUAGE_CODE)
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 159, in _fetch
==> default:     
==> default: app = import_module(appname)
==> default:   File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
==> default:     
==> default: __import__(name)
==> default:   File "/vagrant/expo/gbe/__init__.py", line 1, in <module>
==> default:     
==> default: from receivers import *
==> default:   File "/vagrant/expo/gbe/receivers.py", line 7, in <module>
==> default:     
==> default: from gbe.models import AudioInfo
==> default:   File "/vagrant/expo/gbe/models/__init__.py", line 16, in <module>
==> default:     
==> default: from volunteer_interest import VolunteerInterest
==> default:   File "/vagrant/expo/gbe/models/volunteer_interest.py", line 2, in <module>
==> default:     
==> default: from gbe.models import (
==> default: ImportError
==> default: : 
==> default: cannot import name Volunteer
```

**Comment by BenignCremator** [comment]
IT WORKED!!!  I don't believe it.  It Worked!  Runcoverage gave no errors, none.  Was able to restore db, run migrations, sync db, everything.  It worked.  MWHAHAHAHAHA  It worked.  It worked.

**Pull request merged**
