### PR TITLE
GBE-867: fix lack of import on act change state

### PR DESCRIPTION
**Pull request by bethlakshmi**
This came up when I was testing PR #862, but it is really it’s own problem.  When Act Change State was refactored from views.py into it’s own file, i believe we lose the import for django.contrib.messages.

Added the import and a test so it won’t happen again.

### CODE REVIEW

**Comment by gawaineo** [comment]
Reviewed and tested. Everything looks good. A potential code cleanup (not related to your changes but in the same file) change my editor pointed out is on line #3 in the import statements `(from django.core.exceptions import PermissionDenied)` is not being used anywhere.

**Comment by jonkiparsky** [comment]
@gawaineo Good catch, fixing that.

**Comment by jonkiparsky** [comment]
Oh, oops. Thought that was one of mine! Anyway, I'll push the fix. Sorry @bethlakshmi

**Comment by jonkiparsky** [comment]
Anyway, this looks fine to me. Merging.

**Pull request merged**
