### PR TITLE
Logging with directory restructure.  Working, needs tweaking.

### PR DESCRIPTION
**Pull request by BenignCremator**

### CODE REVIEW

**Comment by BenignCremator** [comment]
Most recent commit, f335033, occurred on 28 Aug 2015.  This brings the logging infrastructure up to the most recent main branch code commit.  It was handled by effectively swapping the previous code for updated code pulled from main and adding logging to it, because logging touches nearly every view in the GBE.

**Comment by jonkiparsky** [comment]
@bethlakshmi Why was this closed?

**Comment by jonkiparsky** [comment]
@BenignCremator Why is expo/gbe/logging_views.py here?

**Comment by BenignCremator** [comment]
On 09/07/2015 04:40 PM, Jon Kiparsky wrote:
> @BenignCremator <https://github.com/BenignCremator> Why is
> expo/gbe/logging_views.py here?

Mistake.  It is a sample of previous views.py with logging to make it 
easier for me to put logging into more recent versions of views.py.  It 
should be deleted, and I am kind of embarrassed that I forgot to delete 
it before I did the git add.

Hunter

**Pull request closed without merging**
