### PR TITLE
GBE-855: Changed column header for review volunteer list

### PR DESCRIPTION
**Pull request by jonkiparsky**

### CODE REVIEW

**Comment by bethlakshmi** [comment]
- pepdiff looks good
- unit test rerun looks good - note to other reviewers, if you (like me) just were reviewing GBE-110, remember to clear your migrated DB and do a removal of your *pyc files.
- manual test looks good

I approve.

**Comment by BenignCremator** [comment]
Found and resolved a couple of pep8 violations.  This threw a file into an non-auto-merge-able state.  Resolved that.  Since neither were more then whitespace tweaks, I feel safe to proceed with testing.

**Comment by BenignCremator** [comment]
Code review looks good.  Pytests also.  Functional tests look... as described in the original ticket.  However, this change has not been made to /volunteer/assign/, so touching that quickly.

**Comment by BenignCremator** [comment]
Retested and everything looks good.  Merging and pruning.

**Pull request merged**
