### PR TITLE
GBE-593: fix show title bug in act scheduling

### LINKED ISSUE #353: Can't use () or . in Show due to schedule_acts URL lookup
I had a test show called "The Bordello (Fri. Late)" in my test database.

It failed on a URL reverse lookup until I changed it to "The Bordello".

I'd much rather we use ids than names for any URL lookup.  We do absolutely nothing to guarantee names are unique, so looking up names will always produce non-deterministic results.

### PR DESCRIPTION
**Pull request by bethlakshmi**
This is the bug I stumbled over last night.  #593 

It also closes #353.

When you navigate to the act scheduler on a show that has the same title as another show, you got an error because we filtered on title, not on private key.

This fixes that.

Example from current test data:

http://gbe2016test.gbeadmin.webfactional.com/scheduler/edit/Show/2518

click on- schedule acts:

http://gbe2016test.gbeadmin.webfactional.com/scheduler/acts/The%20Main%20Event

Note the URL, and you can see the fail on test.  On this build, the URL will be an id, not a title, and the thread will work.

### CODE REVIEW

**Comment by BenignCremator** [comment]
Code review and py.tests look good, moving on to functional test.

**Comment by BenignCremator** [comment]
BLOCKER: Went to URL listed in original ticket, altered some data (changed a backlight color from white to OFF), and pressed submit. Error when submitting an edit:
MultipleObjectsReturned at /acttechinfo/edit/389
get() returned more than one Show -- it returned 2!

Is this is the same error that this ticket covers in a different but dependent location? Either way, submit is broken, and I can not approve until there is basic functionality in standard cases.

**Comment by bethlakshmi** [comment]
Sweet!  Great find! 

Will fix!

Thank so, so much for catching that!  I came at the code a different way and didn't even realize I had missed the original target problem.  Sigh.

**Comment by gawaineo** [comment]
Ran py.test, test results look good. Verified page visually, the event_id is being used instead of the event/show name. Everything looks good to me, I approve.

**Comment by bethlakshmi** [comment]
OK, @BenignCremator - I think I covered the original bug, as well, now.
Please re review

**Comment by BenignCremator** [comment]
Much better.  Functionality works, submission works, py.test is happy, and code review looks good.  Approving and merging.

**Pull request merged**
