### PR TITLE
Gbe 531: Unit Tests Completely Broken

### PR DESCRIPTION
**Pull request by jonkiparsky**
Fixed all but four of the broken tests. The remaining four are commented out, and will be deleted in a month unless someone can get them to pass.

### CODE REVIEW

**Comment by bethlakshmi** [comment]
hrm... I must be doing something wrong... I did:

(in my mac terminal):
vagrant reload --provision
vagrant up
vagrant ssh

(in vagrant):
cd /vagrant/expo
./manage.py test

Entered "yes" to recreating the test database and got:

Got an error recreating the test database: (1044, "Access denied for user 'django_user'@'%' to database 'test_gbe_dev'")

What's wrong with my DB access?  is there something else I should be doing??

**Comment by BenignCremator** [comment]
On 09/24/2015 10:32 PM, bethlakshmi wrote:

> hrm... I must be doing something wrong... I did:
...
> What's wrong with my DB access? is there something else I should be doing??

You need to give the django_user access to test_gbe_dev in addition to 
gbe_dev.  Run this script, try again, and I should work after deleting 
the DB.

Hunter


  mysql -u root -proot -e "DROP DATABASE IF EXISTS test_gbe_dev"
  mysql -u root -proot  -e "CREATE DATABASE test_gbe_dev"
  mysql -u root -proot  -e "USE test_gbe_dev"
  mysql -u root -proot  -e "GRANT ALL ON test_gbe_dev.* to 'django_user'@'%' IDENTIFIED BY 'secret' WITH GRANT OPTION"
  mysql -u root -proot  -e "GRANT ALL ON test_gbe_dev.* to 'django_user'@'%' IDENTIFIED BY 'secret'"

**Comment by jonkiparsky** [comment]
Ah, I see the problem. The new vagrant file takes care of this, but it's
not on this branch. Pull branch GBE-531, then merge master into it:

$ git checkout GBE-531
$ git pull
$ git merge master

The merge with master should go without any trouble. Then you'll have the
fixed tests and the new Vagrantfile, and it should go smoothly.
Or better still, I'll commit a merge with master, so it'll have the latest
accepted code, plus the new tests.

**Comment by jonkiparsky** [comment]
I've updated this to include the current code from master. Try it now - vagrant destroy, vagrant up, vagrant ssh, then:

`
vagrant@blueprint:~$ cd /vagrant
vagrant@blueprint:/vagrant$ expo/manage.py test expo/tests/
nosetests expo/tests/ --verbosity=1
Creating test database for alias 'default'...
No filer contentypes to migrate. This is probably because migrate is running on a new database.
     - renaming cmsplugin_filervideo to cmsplugin_filer_video_filervideo
     - renaming cmsplugin_filervideo to cmsplugin_filer_video_filervideo
     - renaming cmsplugin_filerteaser to cmsplugin_filer_teaser_filerteaser
     - renaming cmsplugin_filerteaser to cmsplugin_filer_teaser_filerteaser
     - renaming cmsplugin_filerlinkplugin to cmsplugin_filer_link_filerlinkplugin
     - renaming cmsplugin_filerlinkplugin to cmsplugin_filer_link_filerlinkplugin
     - renaming cmsplugin_filerimage to cmsplugin_filer_image_filerimage
     - renaming cmsplugin_filerimage to cmsplugin_filer_image_filerimage
     - renaming cmsplugin_filerfolder to cmsplugin_filer_folder_filerfolder
     - renaming cmsplugin_filerfolder to cmsplugin_filer_folder_filerfolder
     - renaming cmsplugin_filerfile to cmsplugin_filer_file_filerfile
     - renaming cmsplugin_filerfile to cmsplugin_filer_file_filerfile
Cannot migrate users to use_structure permission, please add the permission manually
..........................................................................................................................
----------------------------------------------------------------------
Ran 122 tests in 10.769s

OK
Destroying test database for alias 'default'...
vagrant@blueprint:/vagrant$ 
`

**Comment by BenignCremator** [comment]
On 09/24/2015 11:11 PM, Jon Kiparsky wrote:

> I've updated this to include the current code from master. Try it now -

Same result for me.  7 errors, only in ticketing.

Hunter

**Comment by jonkiparsky** [comment]
Weird. I'll look into it.

**Comment by jonkiparsky** [comment]
I still can't reproduce. Can we look at this together? I want to see exactly what you're doing.

**Comment by bethlakshmi** [comment]
I had the same problem as Hunter.
I just sent Jon logs.

If I change:

    fixtures = ['expo/tests/fixtures/tickets_to_events.json']

in test_get_tickets.py to 

    fixtures = ['tests/fixtures/tickets_to_events.json']

Then I get 2 errors, instead of 7

**Comment by bethlakshmi** [comment]
the two lines of change I just committed means all tests pass, with one warning:

vagrant@blueprint:/vagrant/expo$ ./manage.py test
nosetests --verbosity=1
Creating test database for alias 'default'...
No filer contentypes to migrate. This is probably because migrate is running on a new database.
     - renaming cmsplugin_filervideo to cmsplugin_filer_video_filervideo
     - renaming cmsplugin_filervideo to cmsplugin_filer_video_filervideo
     - renaming cmsplugin_filerteaser to cmsplugin_filer_teaser_filerteaser
     - renaming cmsplugin_filerteaser to cmsplugin_filer_teaser_filerteaser
     - renaming cmsplugin_filerlinkplugin to cmsplugin_filer_link_filerlinkplugin
     - renaming cmsplugin_filerlinkplugin to cmsplugin_filer_link_filerlinkplugin
     - renaming cmsplugin_filerimage to cmsplugin_filer_image_filerimage
     - renaming cmsplugin_filerimage to cmsplugin_filer_image_filerimage
     - renaming cmsplugin_filerfolder to cmsplugin_filer_folder_filerfolder
     - renaming cmsplugin_filerfolder to cmsplugin_filer_folder_filerfolder
     - renaming cmsplugin_filerfile to cmsplugin_filer_file_filerfile
     - renaming cmsplugin_filerfile to cmsplugin_filer_file_filerfile
Cannot migrate users to use_structure permission, please add the permission manually
........................./usr/local/lib/python2.7/dist-packages/django/core/management/commands/loaddata.py:216: UserWarning: No fixture named 'rooms' found.
  warnings.warn("No fixture named '%s' found." % fixture_name)

.................................................................................................
----------------------------------------------------------------------
Ran 122 tests in 14.593s

OK

=======

Something is different between Jon's and my environment that mean that default locations of test fixtures are different.

**Comment by jonkiparsky** [comment]
> the two lines of change I just committed means all tests pass,

Confused. Committed where?

**Comment by jonkiparsky** [comment]
Okay, made some more changes. 
Should work now IF you run the tests from GBE2/expo
Running tests from GBE/ will fail. 
Also got rid of the warnings, and added in the stuff from ticket GBE-358 since it was hard to work with different fixes on different branched.

**Comment by bethlakshmi** [comment]
(insert mad cackling here)
Woohoohohohohoho!!

it works!

**Comment by jonkiparsky** [comment]
Huzzah! Harrumble!

sent from my handy. typos are just part of the fun.

**Pull request merged**
