### PR TITLE
Fix for 500 on staff area

### LINKED ISSUE #691: 500 error on http://www.burlesque-expo.com/reports/staff_area/139
Every staff area report now has a 500 error.
Consistent now on my local master, gbe2016test, and gbelive

This worked 6 days ago when I pulled.

error = FieldError at /reports/staff_area/367

Cannot resolve keyword 'conference' into field. Choices are: contained_events, container_event, eventitem, id, max_volunteer, resources_allocated, schedulable_ptr, starttime

### PR DESCRIPTION
**Pull request by bethlakshmi**
Closes #691

Includes introduction of a test to catch this.

### CODE REVIEW

**Comment by jonkiparsky** [comment]
I'm getting a test failure in test_volunteer_management.py

**Comment by jonkiparsky** [comment]
Crap. Same failure on master. WTF?

**Comment by jonkiparsky** [comment]
Looks like the test failure is unrelated, and this fixes the issue it's meant to fix. Merging. Pulling hair out over failing test.

**Comment by bethlakshmi** [comment]
!!!  ???
I'm not getting that.  Just re-re tested.

**Comment by jonkiparsky** [comment]
Might be local - my local is a mess after this last week.

**Pull request merged**
